version: '3'

volumes:
  datafiles:

services:

  okappdb:
    image: mysql:8.0.0
    volumes:
      - ./Host-Dbs:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: OkAppDB
      MYSQL_ROOT_PASSWORD: 6Bb5gCjPAvATLQWk
      TZ: America/Toronto
    ports:
      - "3306:3306"

  okapp_host:
    image: eduardoamparo/okapp-host
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDev
      TZ: America/Toronto
    ports:
      - "21021:80"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
    restart: always
    depends_on:
      - okappdb