// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OkApp.EntityFrameworkCore;

namespace OkApp.Migrations
{
    [DbContext(typeof(OkAppDbContext))]
    [Migration("20190521025246_InitialDbCollation")]
    partial class InitialDbCollation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        { }
    }
}

